 IDENTIFICATION DIVISION.
 PROGRAM-ID. main.
 DATA DIVISION.
 WORKING-STORAGE SECTION.

 77  dummy  NATIVE-2 VALUE  17.

 77  nat  NATIVE-2 VALUE  1.
     88 nata       VALUE  1.
     88 nataa      VALUE  -1.
     88 natb       VALUE  2.
     88 natc       VALUE  3 thru 4.
     88 natd       VALUE  5 6.
     88 nate       VALUE  100 thru 104 17000 thru 22000.


* PCI: these constants are described as PDT^DESC^char.
* char is XX and constants like "CD" are described as have len = 2
* in PCI's storage^info.  Even though the parent
* is XX, the constant generated by COBOL85 and NMCOBOL for cha is "A"
* with len = 1.  I have no idea how VI/Inspect was supposed to compare that
* value with an XX variable.  The stmt Move "A" to char pads a space, "A ".
* DWARF:  DW_ATE_unsigned_char but actual constant data shows "(null)"

  77  char  PIC XX  VALUE  "EM".
      88 cha        VALUE  "A".
      88 chb        VALUE  "B".
      88 chc        VALUE  "CD" thru "EF".
      88 chd        VALUE  "GH" "JK".
      88 che        VALUE  "LM" thru "NP" "RS" thru "TU".

* PCI: these constants are in binary, they are not "2" as in memory.

  77  nu PIC 99  VALUE  17.
      88 nua     VALUE  1.
      88 nub     VALUE  2.
      88 nuc     VALUE  22 thru 47.
      88 nud     VALUE  55 66.
      88 nue     VALUE  10 thru 14 88 thru 99.


* signed trailing embedded
* PCI describes the 88 constants as PDT^DESC^bin^sign

  77  te PIC S99 VALUE 17.
      88 tea     VALUE 22.


* signed trailing separate
* PCI describes the 88 contants as PDT^DESC^bin^sign

  77  ts Display  Pic S99   Sign is Trailing Separate VALUE 18.
      88 tsa     VALUE 23.


* signed leading embedded
* PCI describes the 88 contants as PDT^DESC^bin^sign

  77  le Display  Pic S99   Sign is Leading VALUE  2.
      88 lea     VALUE 24.


* signed leading separate
* PCI describes the 88 contants as PDT^DESC^bin^sign

  77  ls Display Pic S99   Sign is Leading Separate VALUE 19.
      88 lsa     VALUE 25.

* packed signed
* PCI describes the 88 contants as PDT^DESC^bin^sign
  77  ps PIC S99 COMP-3   VALUE 17.
      88 psa     VALUE 26.

* packed unsigned
* PCI describes the 88 contants as PDT^DESC^bin^sign
  77  pu PIC  99 COMP-3 VALUE 18.
      88 pua     VALUE 27.

 PROCEDURE DIVISION.
 main-start.

   Display "Start main".
   Move "A" to char.
   Move 22 to dummy.
   Move 2  to nat.
   Move 22 to nu.
   Move "23" to nu.
   Display "End main".

 END PROGRAM main.

