import path from "path";
import { ICOBOLSettings } from "../../config/IConfiguration";

/**
 * Utility for generating Makefile-style dependency lines for COBOL source files.
 *
 * Output format:
 * - Header comments describing source and generator
 * - One target rule mapping `<program>.o` to source + copybooks
 * - Optional unresolved copybook comments for diagnostics
 */
export class MakeDep {
    /**
     * Creates an in-memory dependency file representation.
     *
     * @param settings Active COBOL settings controlling generation behavior.
     * @param sn Source filename (full or relative path).
     * @param copyBooksNames Resolved copybook paths used by the source file.
     * @param processUnUsedCopyBooks Unresolved copybook names collected during parse.
     * @param activeDocumentFilename Document name used for descriptive header output.
     * @returns Array of text lines suitable for writing to a dependency file.
     */
    public static CreateDependencyFile(settings: ICOBOLSettings, sn: string, copyBooksNames: Array<string>, processUnUsedCopyBooks: Array<string>, activeDocumentFilename: string): Array<string> {
        // String-builder style buffer used by callers to persist to disk.
        const sb: Array<string> = [];

        // Feature flag guard: no output when dependency generation is disabled.
        if (settings.makefile_dependency_file === false) {
            return sb;
        }

        // Build target names using source basename without extension.
        const sn_with_no_ext = path.basename(sn, path.extname(sn));
        const sn_base = path.basename(sn);

        // Header comments improve traceability when debugging generated files.
        if (activeDocumentFilename !== undefined && activeDocumentFilename.length !== 0) {
            sb.push(`# Make dependency file for ${path.basename(activeDocumentFilename)}`);
        }
        sb.push(`# Generated by VSCode COBOL extension`);;

        // Start rule line; append continuation marker when at least one copybook exists.
        let maxCopybooks = copyBooksNames.length;
        const hasCopyBooks = maxCopybooks > 0 ? ' \\' : '';

        // Toggle between full source path and basename based on user preference.
        if (settings.makefile_dependancy_fullpath) {
            sb.push(`${sn_with_no_ext}.o: ${sn}${hasCopyBooks}`);
        } else {
            sb.push(`${sn_with_no_ext}.o: ${sn_base}${hasCopyBooks}`);
        }

        // Add each resolved copybook as a dependency continuation line.
        for (const key of copyBooksNames) {
            const hasSlash = maxCopybooks !== 1 ? ' \\' : '';
            if (settings.makefile_dependancy_fullpath) {
                sb.push(`\t${key}${hasSlash}`);
            } else {
                sb.push(`\t${path.basename(key)}${hasSlash}`);
            }
            maxCopybooks--;
        }

        // Preserve unresolved copybook names as comments for follow-up troubleshooting.
        for (const key of processUnUsedCopyBooks) {
            sb.push(`# Unresolved: ${key}`);
        }

        return sb;
    }
}
